AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ClusterName:
    Type: "String"
    Default: "Two_Node_Cluster"
  EmrRelease:
    Type: "String"
    Default: "emr-6.4.0"
    AllowedValues:
    - "emr-6.4.0"
  ClusterInstanceType:
    Type: "String"
    Default: "m5.xlarge"
    AllowedValues:
    - "m5.xlarge"
    - "m5.2xlarge"
    - "m5.4xlarge"
  CoreInstanceCount:
    Type: Number
    Default: 1
    AllowedValues:
    - 1
    - 2
  VpcName:
    Type: "String"
    Default: "main"
  SubnetName:
    Type: "String"
    Default: "Private-1A"

Resources:
  EmrCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
      - Name: Spark
      - Name: Livy
      - Name: JupyterEnterpriseGateway
      - Name: Hive
      - Name: Presto
      Configurations:
      - Classification: presto-connector-hive
        ConfigurationProperties:
          hive.metastore: glue
      EbsRootVolumeSize: '15'
      AutoTerminationPolicy:
        IdleTimeout: 7200
      Name: !Ref ClusterName
      Tags:
        - Key: type
          Value: admin
      JobFlowRole: EMR_EC2_Admin_Role
      ServiceRole: EMR_DefaultRole
      ReleaseLabel: !Ref EmrRelease
      VisibleToAllUsers: true
      LogUri:
        Fn::Sub: 's3://aws-logs-${AWS::AccountId}-${AWS::Region}/elasticmapreduce/'
      Instances:
        TerminationProtected: false
        Ec2SubnetId:
          Fn::ImportValue:
            Fn::Sub: '${VpcName}-PrivateSubnet'
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref ClusterInstanceType
        CoreInstanceGroup:
          InstanceCount: !Ref CoreInstanceCount
          InstanceType: !Ref ClusterInstanceType
          Market: ON_DEMAND
          Name: Core